                  # Configuration File for CBShop #

##############################################################################
#                                                                            #
#   This plugin was developed for specific use on the CubeBeaters server by: #                             #
#     - Systemx86                                                            #
#   If you are experiencing some customization issues please                 #
#   let me know what you would like to be customizable, so that I can        #
#   add it to this plugin allowing more people to use it for their servers.  #
#                                                                            #
##############################################################################


###############################
#                             #
#                             #
#     ITEMS CONFIGURATION     #
#                             #
#                             #
###############################

# ALL INVENTORY INDEXES START AT '0' SO IF YOU WANT SOMETHING IN THE FIRST SLOT OF THE INVENTORY 
# TYPE '0' INTO THE "slot" SETTING.
Items:
    Armor:
        Leather:
            head:
                slot: 0
                cost: 200
            chest:
                slot: 1
                cost: 400
            legs:
                slot: 2
                cost: 600
            feet:
                slot: 3
                cost: 300
        Chain:
            head:
                slot: 5
                cost: 1000
            chest:
                slot: 6
                cost: 1500
            legs:
                slot: 7
                cost: 700
            feet:
                slot: 8
                cost: 400
        Iron:
            head:
                slot: 9
                cost: 800
            chest:
                slot: 10
                cost: 1200
            legs:
                slot: 11
                cost: 600
            feet:
                slot: 12
                cost: 300
        Gold:
            head:
                slot: 14
                cost: 2500
            chest:
                slot: 15
                cost: 4000
            legs:
                slot: 16
                cost: 1800
            feet:
                slot: 17
                cost: 1200
        Diamond:
            head:
                slot: 18
                cost: 5000
            chest:
                slot: 19
                cost: 8500
            legs:
                slot: 20
                cost: 4250
            feet:
                slot: 21
                cost: 3800
    Weapons:
        Swords:
            Wood:
                slot: 0
                cost: 50
            Stone:
                slot: 1
                cost: 100
            Iron:
                slot: 2
                cost: 400
            Gold:
                slot: 3
                cost: 800
            Diamond:
                slot: 4
                cost: 1700
        Archery:
            Bow:
                slot: 9
                cost: 1000
            Arrow:
                slot: 10
                amount: 64
                cost: 1000
    Tools:
        Pickaxe:
            Wood:
                slot: 0
                cost: 50
            Stone:
                slot: 1
                cost: 100
            Iron:
                slot: 2
                cost: 600
            Gold:
                slot: 3
                cost: 1000
            Diamond:
                slot: 4
                cost: 2200
        Axe:
            Wood:
                slot: 9
                cost: 50
            Stone:
                slot: 10
                cost: 100
            Iron:
                slot: 11
                cost: 600
            Gold:
                slot: 12
                cost: 1200
            Diamond:
                slot: 13
                cost: 1500
        Shovel:
            Wood:
                slot: 18
                cost: 50
            Stone:
                slot: 19
                cost: 100
            Iron:
                slot: 20
                cost: 600
            Gold:
                slot: 21
                cost: 1200
            Diamond:
                slot: 22
                cost: 1400
    Mining:
        Ore:
            Coal:
                slot: 0
                amount: 16
                cost: 250
            Iron:
                slot: 1
                amount: 16
                cost: 500
            Gold:
                slot: 2
                amount: 16
                cost: 600
            Diamond:
                slot: 3
                amount: 16
                cost: 800
            Redstone:
                slot: 4
                amount: 16
                cost: 100
            Emerald:
                slot: 5
                amount: 16
                cost: 1200
        Ingots:
            Lapis:
                slot: 9
                amount: 16
                cost: 250
            Iron:
                slot: 10
                amount: 16
                cost: 800
            Gold:
                slot: 11
                amount: 16
                cost: 1200
            Diamond:
                slot: 12
                amount: 16
                cost: 1600
            Emerald:
                slot: 13
                amount: 16
                cost: 2200