name: CBShop
main: net.cubebeaters.CBShop
version: 1.0
author: Systemx86
depend: [Vault]
commands:
    Shop:
        description: Opens the Shop GUI so that players can purchase Items.
        permission: cbshop.shop
        usage: &c Incorrect command usage. The correct usage is /Shop