name: CBShop
main: net.cubebeaters.CBShop
version: 1.2.0
author: Systemx86
commands:
    Shop:
        description: Opens the Shop GUI.
        permission: cbshop.shop
        usage: &c Incorrect command usage. /Shop